-- ============================================================================
-- QUERY 5: PORTAL CMS, CENTRAL RESOURCES REPOSITORY & ADMIN DELEGATION
-- Database: Central Supabase Instance
-- Purpose: 
--   1. Add portal-specific administrator flag on public.profiles (is_portal_admin).
--   2. Create public.portal_resources table to store & auto-arrange all verified resources.
--   3. Create public.portal_submissions table for student submissions & FEEDBACK.
--   4. Implement Row Level Security (RLS) policies for public reading & admin management.
--   5. Implement RPC functions for Admin User Selector modal & submission approval.
--   6. Migrate & seed all 63 catalog records across 10 categories from json/*.json.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- STEP 1: Add is_portal_admin to public.profiles
-- ----------------------------------------------------------------------------
ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS is_portal_admin BOOLEAN NOT NULL DEFAULT false;

-- Add index on is_portal_admin
CREATE INDEX IF NOT EXISTS idx_profiles_is_portal_admin ON public.profiles(is_portal_admin);

-- Comment
COMMENT ON COLUMN public.profiles.is_portal_admin IS 'Designates administrator privileges strictly within the oU1TS Portal project';

-- ----------------------------------------------------------------------------
-- STEP 2: Create public.portal_resources Table
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_resources (
    id TEXT PRIMARY KEY,
    category TEXT NOT NULL,
    title TEXT NOT NULL,
    description TEXT DEFAULT '',
    url TEXT DEFAULT '',
    copy_url TEXT DEFAULT '',
    icon JSONB DEFAULT '{}'::JSONB,
    links JSONB DEFAULT '[]'::JSONB,
    tags TEXT[] DEFAULT ARRAY[]::TEXT[],
    extra_data JSONB DEFAULT '{}'::JSONB,
    status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('approved', 'pending', 'rejected', 'archived')),
    sort_order INTEGER NOT NULL DEFAULT 0,
    submitted_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_portal_resources_cat_status ON public.portal_resources(category, status);
CREATE INDEX IF NOT EXISTS idx_portal_resources_sort ON public.portal_resources(sort_order);
CREATE INDEX IF NOT EXISTS idx_portal_resources_submitted ON public.portal_resources(submitted_by);

-- ----------------------------------------------------------------------------
-- STEP 3: Create public.portal_submissions Table (Resources + FEEDBACK)
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.portal_submissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    submission_type TEXT NOT NULL DEFAULT 'resource' CHECK (submission_type IN ('resource', 'feedback')),
    category TEXT DEFAULT 'general',
    title TEXT,
    description TEXT,
    url TEXT,
    submitter_name TEXT,
    submitter_email TEXT,
    submitter_department TEXT,
    submitter_batch TEXT,
    feedback_type TEXT DEFAULT 'general',
    rating INTEGER CHECK (rating >= 1 AND rating <= 5),
    details JSONB DEFAULT '{}'::JSONB,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'reviewed', 'resolved')),
    admin_notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_portal_submissions_status ON public.portal_submissions(status);
CREATE INDEX IF NOT EXISTS idx_portal_submissions_type ON public.portal_submissions(submission_type);

-- ----------------------------------------------------------------------------
-- STEP 4: Helper & Security Functions
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.is_portal_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
    SELECT COALESCE(
        (SELECT is_portal_admin FROM public.profiles WHERE id = auth.uid()),
        false
    );
$$;

-- Enable Row Level Security
ALTER TABLE public.portal_resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portal_submissions ENABLE ROW LEVEL SECURITY;

-- Clean existing policies
DROP POLICY IF EXISTS "Public read approved resources" ON public.portal_resources;
DROP POLICY IF EXISTS "Admin insert resources" ON public.portal_resources;
DROP POLICY IF EXISTS "Admin update resources" ON public.portal_resources;
DROP POLICY IF EXISTS "Admin delete resources" ON public.portal_resources;

DROP POLICY IF EXISTS "Public insert submissions" ON public.portal_submissions;
DROP POLICY IF EXISTS "Admin select submissions" ON public.portal_submissions;
DROP POLICY IF EXISTS "Admin update submissions" ON public.portal_submissions;
DROP POLICY IF EXISTS "Admin delete submissions" ON public.portal_submissions;

-- Policies for portal_resources
CREATE POLICY "Public read approved resources"
    ON public.portal_resources
    FOR SELECT
    USING (status = 'approved' OR public.is_portal_admin());

CREATE POLICY "Admin insert resources"
    ON public.portal_resources
    FOR INSERT
    WITH CHECK (public.is_portal_admin());

CREATE POLICY "Admin update resources"
    ON public.portal_resources
    FOR UPDATE
    USING (public.is_portal_admin())
    WITH CHECK (public.is_portal_admin());

CREATE POLICY "Admin delete resources"
    ON public.portal_resources
    FOR DELETE
    USING (public.is_portal_admin());

-- Policies for portal_submissions
CREATE POLICY "Public insert submissions"
    ON public.portal_submissions
    FOR INSERT
    WITH CHECK (true);

CREATE POLICY "Admin select submissions"
    ON public.portal_submissions
    FOR SELECT
    USING (public.is_portal_admin());

CREATE POLICY "Admin update submissions"
    ON public.portal_submissions
    FOR UPDATE
    USING (public.is_portal_admin())
    WITH CHECK (public.is_portal_admin());

CREATE POLICY "Admin delete submissions"
    ON public.portal_submissions
    FOR DELETE
    USING (public.is_portal_admin());

-- ----------------------------------------------------------------------------
-- STEP 5: RPC Functions for Admin Management & Approvals
-- ----------------------------------------------------------------------------

-- Function: Get all users who have logged into the portal project
CREATE OR REPLACE FUNCTION public.get_portal_users()
RETURNS TABLE (
    id UUID,
    full_name TEXT,
    email TEXT,
    student_id TEXT,
    department TEXT,
    batch TEXT,
    avatar_url TEXT,
    project_tags TEXT[],
    is_portal_admin BOOLEAN,
    last_seen_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    IF NOT public.is_portal_admin() THEN
        RAISE EXCEPTION 'Access denied. Caller is not an authorized portal administrator.';
    END IF;

    RETURN QUERY
    SELECT 
        p.id,
        p.full_name,
        p.email,
        p.student_id,
        p.department,
        p.batch,
        p.avatar_url,
        p.project_tags,
        p.is_portal_admin,
        p.last_seen_at,
        p.created_at
    FROM public.profiles p
    WHERE 'portal' = ANY(p.project_tags)
    ORDER BY p.is_portal_admin DESC, p.last_seen_at DESC NULLS LAST;
END;
$$;

-- Function: Delegate or revoke portal admin role (admin-only)
CREATE OR REPLACE FUNCTION public.set_portal_admin(
    target_user_id UUID,
    grant_admin BOOLEAN
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_target_exists BOOLEAN;
BEGIN
    IF NOT public.is_portal_admin() THEN
        RAISE EXCEPTION 'Access denied. Only an existing portal administrator can update admin roles.';
    END IF;

    SELECT ('portal' = ANY(project_tags)) INTO v_target_exists
    FROM public.profiles
    WHERE id = target_user_id;

    IF v_target_exists IS NULL THEN
        RAISE EXCEPTION 'Target user does not exist in public.profiles.';
    END IF;

    UPDATE public.profiles
    SET is_portal_admin = grant_admin,
        updated_at = NOW()
    WHERE id = target_user_id;

    RETURN jsonb_build_object(
        'success', true,
        'user_id', target_user_id,
        'is_portal_admin', grant_admin
    );
END;
$$;

-- Function: Auto-approve a resource submission and publish to portal_resources
CREATE OR REPLACE FUNCTION public.approve_resource_submission(p_sub_id BIGINT)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    v_sub public.portal_submissions%ROWTYPE;
    v_res_id TEXT;
    v_slug TEXT;
BEGIN
    IF NOT public.is_portal_admin() THEN
        RAISE EXCEPTION 'Access denied. Caller is not a portal administrator.';
    END IF;

    SELECT * INTO v_sub FROM public.portal_submissions WHERE id = p_sub_id;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Submission #% not found.', p_sub_id;
    END IF;

    -- Slugify title
    v_slug := LOWER(REGEXP_REPLACE(COALESCE(v_sub.title, 'resource'), '[^a-zA-Z0-9]+', '-', 'g'));
    v_res_id := COALESCE(v_sub.category, 'resource') || '-' || TRIM(BOTH '-' FROM v_slug);

    INSERT INTO public.portal_resources (
        id,
        category,
        title,
        description,
        url,
        copy_url,
        icon,
        links,
        tags,
        extra_data,
        status,
        sort_order
    )
    VALUES (
        v_res_id,
        COALESCE(v_sub.category, 'materials'),
        COALESCE(v_sub.title, 'Community Resource'),
        COALESCE(v_sub.description, ''),
        COALESCE(v_sub.url, ''),
        COALESCE(v_sub.url, ''),
        jsonb_build_object('type', 'icon', 'class', 'fa-solid fa-link'),
        '[]'::JSONB,
        ARRAY[]::TEXT[],
        COALESCE(v_sub.details, '{}'::JSONB),
        'approved',
        0
    )
    ON CONFLICT (id) DO UPDATE SET
        title = EXCLUDED.title,
        description = EXCLUDED.description,
        url = EXCLUDED.url,
        status = 'approved',
        updated_at = NOW();

    UPDATE public.portal_submissions
    SET status = 'approved',
        updated_at = NOW()
    WHERE id = p_sub_id;

    RETURN jsonb_build_object(
        'success', true,
        'resource_id', v_res_id,
        'submission_id', p_sub_id
    );
END;
$$;

-- ----------------------------------------------------------------------------
-- STEP 6: Seed Catalog Data (63 Items from JSON catalogs)
-- ----------------------------------------------------------------------------
INSERT INTO public.portal_resources (
    id, category, title, description, url, copy_url, icon, links, tags, extra_data, status, sort_order
) VALUES
('materials-uitsbot', 'materials', 'UITS Bot', 'This is a utility website where students can check their cgpa for each semester, see class routines in a formatted way, and find handwritten notes from previous batch students.', 'http://akibreza.github.io/uitsBOT', 'http://akibreza.github.io/uitsBOT', '{"type":"image","src":"materials-icon/UITS-Bot.webp","background":"linear-gradient(135deg, #e3f2fd, #bbdefb)"}'::JSONB, '[{"label":"Source Code","url":"https://github.com/AkibReza/uitsBOT"},{"label":"Dev","url":"https://github.com/AkibReza"}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 1),
('materials-b1tacad', 'materials', 'b1t Academics', 'b1t Academics is a comprehensive, student-maintained archive for UITS (University) resources. It serves as a central hub for course materials, question banks, class routines, and academic guidelines, aiming to solve the fragmentation of resources across different platforms.', 'https://b1tacad.netlify.app/', 'https://b1tacad.netlify.app/', '{"type":"image","src":"materials-icon/b1t-acad.webp","background":"linear-gradient(135deg, #f3e5f5, #e1bee7)"}'::JSONB, '[{"label":"Source Code","url":"https://github.com/b1tranger/b1t-Acad"},{"label":"Dev","url":"https://github.com/b1tranger"}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 2),
('materials-uniCompanion', 'materials', 'University Companion', 'In this website, you will find the Academic calendar and the previous years'' exam questions of the previous batches of CSE department, UITS. We also added an interactive scheduler where students can update their class records for each week.', 'https://university-companion.netlify.app/', 'https://university-companion.netlify.app/', '{"type":"icon","class":"fa-solid fa-users","color":"#f57c00","background":"linear-gradient(135deg, #fff3e0, #ffe0b2)"}'::JSONB, '[{"label":"Source Code","url":"https://github.com/Zirconium001/echoes_of_the_past","suffix":"(old)"},{"label":"Dev-1","url":"https://github.com/Zirconium001"},{"label":"Dev-2","url":"https://github.com/RabbitJahir"}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 3),
('materials-researchArchive', 'materials', 'UITS Research Archive', 'Experience the next generation of academic discovery. A unified ecosystem for thesis preservation, collaborative research, and scholarly excellence.', 'https://research-uits.rf.gd/', 'https://research-uits.rf.gd/', '{"type":"icon","class":"fa-solid fa-book","color":"#1566e0","background":"linear-gradient(135deg, #fff3e0, #b2e9ff)"}'::JSONB, '[{"label":"Source Code","url":"https://github.com/4xrhd/uits-research-archive"},{"label":"Dev","url":"https://github.com/4xrhd"},{"label":"Socials","url":"https://dinq.me/4xrhd","parentheses":true}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 4),
('tools-handgesture', 'tools', 'Hand Gesture Control System | Soyeb Akram', 'Hands‑free mouse and system control using real‑time AI hand tracking.', 'https://github.com/SoyebAkram/Hand_Gesture_control__system', 'https://github.com/SoyebAkram/Hand_Gesture_control__system', '{"type":"icon","class":"fa-solid fa-robot","color":"#1976d2","background":"linear-gradient(135deg, #e3f2fd, #bbdefb)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 1),
('tools-blooddonation', 'tools', 'Blood Donation Network - UITS', 'We intend to create a network of donators, under certain groups where people know each other. This network will have a list containing contact info and previous donation dates to make the Blood Reception faster for the requester. Your single donation can help save up to three lives.<br><br>Join our community of heroes today.', 'https://bd-ou1ts.netlify.app/', 'https://bd-ou1ts.netlify.app/', '{"type":"image","src":"tools-icon/logo-bd.png","background":"linear-gradient(135deg, #e3f2fd, #bbdefb)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 2),
('tools-b1tsched', 'tools', 'b1t Scheduler', 'lightweight, centralized academic assistant that allows students to view their schedules, track tasks, and access academic information efficiently.', 'https://b1tsched.netlify.app/', 'https://b1tsched.netlify.app/', '{"type":"image","src":"tools-icon/b1t-sched.webp","background":"linear-gradient(135deg, #e8f5e9, #c8e6c9)"}'::JSONB, '[{"label":"Source Code","url":"https://github.com/b1tranger/b1t-Sched"},{"label":"Dev","url":"https://github.com/b1tranger"}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 3),
('tools-yourbloodbank', 'tools', 'UBBDMS', 'Save Lives Through Blood Donation UITS Blood Bank & Donor Management System connects blood donors with those in need within UITS university.', 'https://yourbloodbank.netlify.app/', 'https://yourbloodbank.netlify.app/', '{"type":"image","src":"","background":"linear-gradient(135deg, #e8f5e9, #c8e6c9)"}'::JSONB, '[{"label":"Source Code","url":"https://github.com/amit1-ctrl/ubbdms-backend"},{"label":"Dev","url":"https://github.com/amit1-ctrl"}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 4),
('guidance-faq-capstone', 'guidance', 'FAQ on Capstone Project [foxxie]', 'foxxie''s den/foxxie911.github.io | <a class="" href="https://github.com/user-attachments/files/25094431/foxxie911_github_io_FoxxieBlog_articles_2026_FEBRUARY_FAQonC.pdf">Backup</a><br>To address student anxiety regarding Capstone projects,<br>the author has compiled a quick FAQ guide.', 'https://foxxie911.github.io/FoxxieBlog/articles/2026/FEBRUARY/FAQonCapstoneProject.html', 'https://foxxie911.github.io/FoxxieBlog/articles/2026/FEBRUARY/FAQonCapstoneProject.html', '{"type":"icon","class":"fa-solid fa-book","color":"#0288d1","background":"linear-gradient(135deg, #e1f5fe, #b3e5fc)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 1),
('guidance-research-pub', 'guidance', 'গবেষণা প্রকাশের সম্পূর্ণ গাইড [4xrhd]', 'গবেষণা শুধু পেপার লেখা না, এটি একটি দীর্ঘমেয়াদি কৌশল। সেই কৌশলটাকেই সহজভাবে সাজিয়ে দিয়েছি এই ছোট বইটিতে। এই বইটি বিশেষভাবে উপযোগীঃ<br>- অনার্স ও মাস্টার্স শিক্ষার্থী<br>- PhD গবেষক<br>- নতুন ও আগ্রহী গবেষক<br>- যারা বিদেশে উচ্চশিক্ষা বা একাডেমিক ক্যারিয়ার গড়তে চান<br><a class="" href="https://github.com/user-attachments/files/26050275/Complete.Guide.to.Research.Publishing.Azhar.pdf">Backup</a> | <a href="http://fb.me/">Dev</a>', 'https://www.supportkori.com/4xrhd/extras/complete-guide-to-research-publishing-banglav100-azhar-uddin-l17g', 'https://www.supportkori.com/4xrhd/extras/complete-guide-to-research-publishing-banglav100-azhar-uddin-l17g', '{"type":"icon","class":"fa-solid fa-book","color":"#0288d1","background":"linear-gradient(135deg, #e1f5fe, #b3e5fc)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 2),
('ou1ts-community-fb', 'community', 'oU1TS Community', 'Online community, for the students of UITS. Join here to get latest updates on oU1TS initiative.', 'https://facebook.com/groups/1074592960836263/', 'https://facebook.com/groups/1074592960836263/', '{"type":"image","src":"community-icon/oUITS.webp","background":"linear-gradient(135deg, #e3f2fd, #bbdefb);"}'::JSONB, '[{"label":"Telegram","url":"https://t.me/s/oUITS_ORnU"},{"label":"Discord","url":"https://discord.gg/BdmArz6FHY"},{"label":"GitHub","url":"https://github.com/oU1TS"},{"label":"Reddit","url":"https://www.reddit.com/r/oU1TS/"}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 1),
('discord-protein-shake', 'community', 'Protein Shake - Discord', 'The journey once started as a humble place for a few friends sitting together and having a chat. Now, a leading community-driven network open to all.', 'https://discord.gg/weetUpfS5X', 'https://discord.gg/weetUpfS5X', '{"type":"image","src":"community-icon/protein-shake-discord.webp","background":"linear-gradient(135deg, #e3f2fd, #bbdefb);"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 2),
('community-discord', 'community', 'Students Forum of UITS', 'This is the official group of our forum for current students and alumni of the University of Information Technology and Sciences (UITS).', 'https://www.facebook.com/groups/sfuits', 'https://www.facebook.com/groups/sfuits', '{"type":"image","src":"community-icon/sfuits-fb.webp","background":"linear-gradient(135deg, #ede7f6, #d1c4e9);"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 3),
('community-discord-golang', 'community', 'Best Golang Community Ever', '"Education must be free!"- Habibur Rahman (CSE37)', 'https://discord.gg/HUG2W59yUb', 'https://discord.gg/HUG2W59yUb', '{"type":"image","src":"community-icon/golang-community-icon.webp","alt":"UITS Cyber Security Wing","background":"linear-gradient(135deg, #fff3e0, #ffe0b2);"}'::JSONB, '[{"label":"Facebook","url":"https://www.facebook.com/groups/1118405403169990/"},{"label":"Dev","url":"https://www.linkedin.com/in/habibur-r-ahman/"},{"label":"NesoHQ","url":"https://nesohq.org/"}]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 4),
('official-website', 'official', 'UITS Official Website', 'https://uits.ac.bd/', 'https://uits.ac.bd/', 'https://uits.ac.bd/', '{"type":"icon","class":"fa-solid fa-school","color":"#1976d2","background":"linear-gradient(135deg, #e3f2fd, #bbdefb)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 1),
('official-studentportal', 'official', 'Student Portal', 'https://ucam.uits.edu.bd/', 'https://ucam.uits.edu.bd/', 'https://ucam.uits.edu.bd/', '{"type":"icon","class":"fa-solid fa-user-graduate","color":"#f57c00","background":"linear-gradient(135deg, #fff3e0, #ffe0b2)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 2),
('community-github', 'official', 'UITS Cyber Security Wing', 'Welcome to the community page of Cyber Security Wing, UITS Computer Club! We explore cybersecurity through hands-on workshops, CTF challenges, and networking with experts. Join Us!<br><br>Alt: <a href="https://www.facebook.com/uitssec" target="_blank">Facebook</a> | <a href="https://discord.gg/hqBQZzMwce" target="_blank">Discord</a>', 'https://uitssec.github.io/index.html', 'https://uitssec.github.io/index.html', '{"type":"image","src":"https://res.cloudinary.com/b1tranger/image/upload/v1757773769/nobg_UITS_Cyber_Security_Wing_FB_logo_admu5c.png","alt":"UITS Cyber Security Wing","background":"linear-gradient(135deg, #212121, #424242)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 3),
('official-attendance', 'official', 'CSE Attendance Fine', 'This portal allows students of UITS Department of CSE to check their attendance fines for the Spring 2026 semester. Enter your Student ID in the lookup section to view your detailed fine breakdown.<br><a href="https://github.com/mrinmoybiswasU/performance-and-attendance" target="_blank">Source Code</a> | <a href="https://github.com/mrinmoybiswasu" target="_blank">Dev</a>', 'https://mrinmoybiswasu.github.io/performance-and-attendance/', 'https://mrinmoybiswasu.github.io/performance-and-attendance/', '{"type":"image","src":"official-icon/attendance-fine-icon.webp","alt":"Attendance Fine","background":"linear-gradient(135deg, #e8f5e9, #c8e6c9)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 4),
('portfolio-b1tranger', 'portfolios', '@b1tranger/0432410005101088', 'I’m a CSE undergrad at UITS, exploring and learning. I have a deep appreciation for poetry and the Arabic language. | b1tranger.01@gmail.com', 'https://b1tranger.netlify.app/', 'https://uitssec.github.io/', '{"type":"image","src":"portfolio-icon/b1ranger-portfolio.webp","background":"linear-gradient(135deg, #e8f5e9, #c8e6c9)"}'::JSONB, '[]'::JSONB, ARRAY['Development', 'Editing', 'Content Creation']::TEXT[], '{}'::JSONB, 'approved', 1),
('portfolio-chatokjnr', 'portfolios', '@chatok-jnr/0432220005101058', 'I''m always open to discussing new projects, creative ideas, or opportunities to be part of your vision. | md.sakib.hos3n@gmail.com | <a href="https://www.facebook.com/sakib.the.jnr.chatok" target="_blank">Social</a>', 'https://iamchatokjunior.netlify.app/', 'https://iamchatokjunior.netlify.app/', '{"type":"image","src":"portfolio-icon/AnNazmusSakib-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Backend Developer', 'Programmer', 'Mentorship']::TEXT[], '{}'::JSONB, 'approved', 2),
('portfolio-atikshahria', 'portfolios', '@Atik Shahria Opu/0432220005101079', 'I am a backend developer and competitive problem-solver with production experience. I specialize in scalable system architecture, algorithm optimization, and modern development practices. I combine strong computer science fundamentals with practical software engineering skills. | atikshariaropu@gmail.com | <a href="https://www.facebook.com/atikshahriaopu" target="_blank">Social</a>', 'https://atikshahriaopu.netlify.app/', 'https://atikshahriaopu.netlify.app/', '{"type":"image","src":"portfolio-icon/AtikShahriaOpu-portfolio2.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Backend Developer', 'Programmer']::TEXT[], '{}'::JSONB, 'approved', 3),
('portfolio-MahfuzRahman', 'portfolios', '@Md. Mahfuz/0432310005101057', 'I am a Fullstack Developer and Competitive Programmer. I specialize in building performance-critical applications with strict adherence to clean architecture and modern design patterns. | mahfuzur3456@gmail.com | <a href="https://www.linkedin.com/in/md-mahfuz-dev" target="_blank">Social</a>', 'https://mahfuz-portfolio-three.vercel.app/', 'https://mahfuz-portfolio-three.vercel.app/', '{"type":"image","src":"portfolio-icon/MahfuzRahman-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Fullstack Web Developer', 'Competitive Programmer']::TEXT[], '{}'::JSONB, 'approved', 4),
('portfolio-AkibReza', 'portfolios', '@Akib Reza/0432220005101061', 'Final-year Computer Science student with hands-on experience delivering real-world web applications for international clients. I specialize in building responsive frontends, robust backends, and end-to-end features that are reliable, scalable, and ready for production. | akib.reza23@gmail.com | <a href="https://www.facebook.com/alpha.akib" target="_blank">Social</a>', 'https://akibreza.netlify.app/', 'https://akibreza.netlify.app/', '{"type":"image","src":"portfolio-icon/AkibReza-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['MERN Stack Developer']::TEXT[], '{}'::JSONB, 'approved', 5),
('portfolio-AhammedAbdaliKhan', 'portfolios', '@Ahammed Abdali Khan/0432320005101118', 'Hello! I''m Ahmmad, a strategic problem-solver from Dhaka, Bangladesh, currently pursuing my CSE degree at UITS. I am actively preparing for my Master''s in Australia while building security tools in Parrot OS and Kali Linux. | <a href="https://www.facebook.com/ahk.abdali/" target="_blank">Social</a>', 'https://abdali.vercel.app/', 'https://abdali.vercel.app/', '{"type":"image","src":"portfolio-icon/AhammedAbdaliKhan-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Backend Developer', 'Cybersecurity']::TEXT[], '{}'::JSONB, 'approved', 6),
('portfolio-MdKamruzzamanShishir', 'portfolios', '@Md Kamruzzaman Shishir/1814355002', 'I am a professional Web Developer and IT Specialist based in Bangladesh. I specialize in building high-performance websites, managing secure IT infrastructures, and delivering custom digital solutions for businesses worldwide. | info.mkshishir@gmail.com | <a href="https://www.linkedin.com/in/md-kamruzzaman-shishir/" target="_blank">Social</a>', 'https://mkshishir.pages.dev/', 'https://mkshishir.pages.dev/', '{"type":"image","src":"portfolio-icon/MdKamruzzamanShishir-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['IT Specialist', 'Web Developer', 'E-commerce', 'CMS Expertise', 'Infrastructure', 'Database Management']::TEXT[], '{}'::JSONB, 'approved', 7),
('portfolio-SelimReza', 'portfolios', '@Selim Reza/0432410005101150 <span style="color: rgba(255, 255, 255, 0.253);">[ updated ]</span>', 'Blending deep Python, OOP & DSA expertise with AI-powered workflows to ship secured, production-grade systems. Awarded "Developer of the Quarter" at Join Venture AI. | selim.reza.uits@gmail.com | <a href="https://www.linkedin.com/in/selim-reza-dev/" target="_blank">Social</a>', 'https://portfolio.selimreza.dev/', 'https://portfolio.selimreza.dev/', '{"type":"image","src":"portfolio-icon/SelimReza-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Backend Developer', 'Python']::TEXT[], '{}'::JSONB, 'approved', 8),
('portfolio-KaziMdAzharUddinAbeer', 'portfolios', '@Kazi Md. Azhar Uddin Abeer/0432320005101120', 'Specialized in penetration testing, secure DevOps, and building resilient systems. 7+ years of experience in backend development and infrastructure security. | c.azhar@outlook.com | <a href="https://www.facebook.com/4xrhd" target="_blank">Social</a>', 'http://4xrhd.rf.gd', 'http://4xrhd.rf.gd', '{"type":"image","src":"portfolio-icon/KaziMdAzharUddinAbeer-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Pentester', 'DevOps', 'Cybersecurity']::TEXT[], '{}'::JSONB, 'approved', 9),
('portfolio-#', 'portfolios', 'Nafiz Al Zawad/0432220005101041', 'I''m a 4th-year Computer Science student from Bangladesh who believes that great software isn''t just built, it''s refined, tested, and trusted. My journey through development, documentation, and client experience naturally pulled me toward one direction: Software Quality Assurance. | contact@zawad.dev | <a href="https://linkedin.com/in/nafizalzawad" target="_blank">Social</a>', 'https://zawad.dev/', 'https://zawad.dev/', '{"type":"image","src":"portfolio-icon/NafizAlZawad-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['QA Engineer', 'Automation Specialist', 'Documentation']::TEXT[], '{}'::JSONB, 'approved', 10),
('portfolio-safrid', 'portfolios', '@MD Safrid Bhueyan/0432310005101080', 'Building AI-powered scalable mobile solutions. Expert in cross-platform development and machine learning integration. | safridbhueyan@gmail.com<br>Socials: <a href="https://linkedin.com/in/safridbhueyan" target="_blank">LinkedIn</a> | <a href="https://github.com/safridbhueyan" target="_blank">GitHub</a>', 'https://portfolionew-lime-phi.vercel.app/', 'https://portfolionew-lime-phi.vercel.app/', '{"type":"image","src":"portfolio-icon/safrid-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Flutter & ML Engineer']::TEXT[], '{}'::JSONB, 'approved', 11),
('portfolio-MohammadIsmailHossen', 'portfolios', 'Mohammad Ismail Hossen/04325205101003', 'I''m a CS student working my way through cloud engineering, AWS focused. I tend to learn the most random, complex things at the most random times. | <a href="https://www.linkedin.com/in/mohammad-ismail-hossen/" target="_blank">Social</a>', 'https://ismails-nocturne.vercel.app/', 'https://ismails-nocturne.vercel.app/', '{"type":"image","src":"portfolio-icon/MohammadIsmailHossen-portfolio.jpg","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY['Cloud / DevOps Engineer', 'AWS', 'Linux', 'Python']::TEXT[], '{}'::JSONB, 'approved', 12),
('portfolio-JubairAhmed', 'portfolios', 'Jubair Ahammed/0432410005101112', 'With a strong foundation in Computer Science and hands-on expertise in modern web technologies, I thrive on building responsive applications, solving real-world problems through code, and crafting intuitive user interfaces. <br>Socials: <a href="https://www.facebook.com/share/1CYCQoJzyy/" target="_blank">Facebook</a> | <a href="https://www.linkedin.com/in/jubairahammed" target="_blank">LinkedIn</a> | <a href="https://github.com/JubairAhammedJubu" target="_blank">GitHub</a>', 'https://jubairprotfolio.netlify.app/', 'https://jubairprotfolio.netlify.app/', '{"type":"image","src":"portfolio-icon/JubairAhmed-portfolio.webp","background":"linear-gradient(135deg, #f3e5f500, #ffffff00)"}'::JSONB, '[]'::JSONB, ARRAY[]::TEXT[], '{}'::JSONB, 'approved', 13),
('courses-all-4xrhd', 'courses', 'Kazi Md Azhar Uddin Abeer (4xrhd)/azhar_uddin1120@uits.edu.bd', '4xrhd/cse-lab-course All Cse Labs (OLD Curriculum)', 'https://github.com/4xrhd/cse-lab-course', 'https://github.com/4xrhd/cse-lab-course', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['All Courses']::TEXT[], '{"course_category":"All Courses","course_icon":"fa-solid fa-layer-group","rawHtml":"<a href=\"https://github.com/4xrhd/cse-lab-course\" target=\"_blank\">Kazi Md Azhar Uddin Abeer (4xrhd)/azhar_uddin1120@uits.edu.bd</a><p>4xrhd/cse-lab-course<br>All Cse Labs (OLD Curriculum)</p>"}'::JSONB, 'approved', 1),
('courses-spl-b1tranger', 'courses', '@b1tranger/0432410005101088', 'b1tranger/CSE0613112-SPL-Lab', 'https://github.com/b1tranger/CSE0613112-SPL-Lab', 'https://github.com/b1tranger/CSE0613112-SPL-Lab', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Structured Programming Language (CSE0613112-SPL)']::TEXT[], '{"course_category":"Structured Programming Language (CSE0613112-SPL)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/b1tranger/CSE0613112-SPL-Lab\" target=\"_blank\">@b1tranger/0432410005101088</a><p>b1tranger/CSE0613112-SPL-Lab</p>"}'::JSONB, 'approved', 2),
('courses-wad-b1tranger', 'courses', '@b1tranger/0432410005101088', 'b1tranger/CSE0613124-WAD-Lab', 'https://github.com/b1tranger/CSE0613124-WAD-Lab', 'https://github.com/b1tranger/CSE0613124-WAD-Lab', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Web Application Design Lab (CSE0613124)']::TEXT[], '{"course_category":"Web Application Design Lab (CSE0613124)","course_icon":"fa-solid fa-globe","rawHtml":"<a href=\"https://github.com/b1tranger/CSE0613124-WAD-Lab\" target=\"_blank\">@b1tranger/0432410005101088</a><p>b1tranger/CSE0613124-WAD-Lab</p>"}'::JSONB, 'approved', 3),
('courses-oop-b1tranger', 'courses', '@b1tranger/0432410005101088', 'b1tranger/CSE0613122-OOP-Lab', 'https://github.com/b1tranger/CSE0613122-OOP-Lab', 'https://github.com/b1tranger/CSE0613122-OOP-Lab', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Object Oriented Programming (CSE 202/CSE0613122)']::TEXT[], '{"course_category":"Object Oriented Programming (CSE 202/CSE0613122)","course_icon":"fa-solid fa-cubes","rawHtml":"<a href=\"https://github.com/b1tranger/CSE0613122-OOP-Lab\" target=\"_blank\">@b1tranger/0432410005101088</a><p>b1tranger/CSE0613122-OOP-Lab</p>"}'::JSONB, 'approved', 4),
('courses-dbms-b1tranger', 'courses', '@b1tranger/0432410005101088', 'b1tranger/CSE0612216-DBMS-Lab', 'https://github.com/b1tranger/CSE0612216-DBMS-Lab', 'https://github.com/b1tranger/CSE0612216-DBMS-Lab', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Database Management (CSE 301/CSE0612216)']::TEXT[], '{"course_category":"Database Management (CSE 301/CSE0612216)","course_icon":"fa-solid fa-database","rawHtml":"<a href=\"https://github.com/b1tranger/CSE0612216-DBMS-Lab\" target=\"_blank\">@b1tranger/0432410005101088</a><p>b1tranger/CSE0612216-DBMS-Lab</p>"}'::JSONB, 'approved', 5),
('courses-dsa1-b1tranger', 'courses', 'Project', 'b1tranger/CSE0612223-DSA-1-Lab: Codes used in DSA-1 Lab CSE0612223. b1tranger/2D-Game_DSA-project: Lab Project of Data Structures and Algorithms 1 course of UITS. Fork-1 | Fork-2', 'https://github.com/b1tranger/2D-Game_DSA-project', 'https://github.com/b1tranger/2D-Game_DSA-project', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Data Structures and Algorithms - 1 (CSE0612223)']::TEXT[], '{"course_category":"Data Structures and Algorithms - 1 (CSE0612223)","course_icon":"fa-solid fa-diagram-project","rawHtml":"@b1tranger/0432410005101088<br><a href=\"https://github.com/b1tranger/2D-Game_DSA-project\" target=\"_blank\">Project</a> | <a href=\"https://github.com/b1tranger/CSE0612223-DSA-1-Lab\">Lab Codes</a><p class=\"repo-info\">b1tranger/CSE0612223-DSA-1-Lab: Codes used in DSA-1 Lab CSE0612223.<br>b1tranger/2D-Game_DSA-project: Lab Project of Data Structures and Algorithms 1 course of UITS.<br><a href=\"https://github.com/oU1TS/DSA-project-55-3B-088.cse55.b1tranger.ou1ts\" target=\"_blank\">Fork-1</a> | <a href=\"https://github.com/oU1TS/CSE0612223-DSA-1-Lab\" target=\"_blank\">Fork-2</a></p>"}'::JSONB, 'approved', 6),
('courses-dsa1-robiul', 'courses', '@Md. Robiul Hassan/0432310005101096', 'Building-a-To-Do-List-Application-with-C | Backup 0432310005101096@uits.edu.bd | +8801997601347 (WhatsApp)', 'https://drive.google.com/drive/u/0/folders/1sQzOBsZK6u9HCRU-uO0Jdg8c7LRak4XL', 'https://drive.google.com/drive/u/0/folders/1sQzOBsZK6u9HCRU-uO0Jdg8c7LRak4XL', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Data Structures and Algorithms - 1 (CSE0612223)']::TEXT[], '{"course_category":"Data Structures and Algorithms - 1 (CSE0612223)","course_icon":"fa-solid fa-diagram-project","rawHtml":"<a href=\"https://drive.google.com/drive/u/0/folders/1sQzOBsZK6u9HCRU-uO0Jdg8c7LRak4XL\" target=\"_blank\">@Md. Robiul Hassan/0432310005101096</a><p>Building-a-To-Do-List-Application-with-C | <a href=\"https://t.me/oUITS_res/2906/3832\" target=\"_blank\">Backup</a><br>0432310005101096@uits.edu.bd | +8801997601347 (WhatsApp)</p>"}'::JSONB, 'approved', 7),
('courses-sesa-b1tranger', 'courses', '@b1tranger/0432410005101088', 'b1tranger/Support-Hero_SESA-Lab-Project "Support Hero" is a community-driven platform where users can create and accept support services, donate transparently, and help build a network of trust and assistance. This is a Lab project for our Software Engineering and System Analysis Lab (CSE0613226). Dev-1(88) , Dev-2(112) , Dev-3(70) , Dev-4(75) | Fork', 'https://github.com/b1tranger/Support-Hero_SESA-Lab-Project', 'https://github.com/b1tranger/Support-Hero_SESA-Lab-Project', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Software Engineering and System Analysis Lab (CSE0613226)']::TEXT[], '{"course_category":"Software Engineering and System Analysis Lab (CSE0613226)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/b1tranger/Support-Hero_SESA-Lab-Project\" target=\"_blank\">@b1tranger/0432410005101088</a><p>b1tranger/Support-Hero_SESA-Lab-Project<br>\"Support Hero\" is a community-driven platform where users can create and accept support services, donate transparently, and help build a network of trust and assistance. This is a Lab project for our Software Engineering and System Analysis Lab (CSE0613226).<br><a href=\"https://github.com/b1tranger\">Dev-1(88)</a>, <a href=\"https://github.com/JubairAhammedJubu\">Dev-2(112)</a>, <a href=\"https://github.com/Amit12Roy\">Dev-3(70)</a>, Dev-4(75) | <a href=\"https://github.com/oU1TS/Support-Hero_SESA-Lab-Project.cse55.b1tranger.ou1ts\">Fork</a></p>"}'::JSONB, 'approved', 8),
('courses-sesa-sadiasemim139-ops', 'courses', '@Sadia Islam/0432410005101096', 'sadiasemim139-ops/sesa software_Engineering-and-system-Analysis. Dev-1(96) , Dev-2(58) , Dev-3(63) , Dev-4(93) | Fork', 'https://github.com/sadiasemim139-ops/sesa', 'https://github.com/sadiasemim139-ops/sesa', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Software Engineering and System Analysis Lab (CSE0613226)']::TEXT[], '{"course_category":"Software Engineering and System Analysis Lab (CSE0613226)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/sadiasemim139-ops/sesa\" target=\"_blank\">@Sadia Islam/0432410005101096</a><p>sadiasemim139-ops/sesa<br>software_Engineering-and-system-Analysis.<br><a href=\"https://github.com/sadiasemim139-ops\" target=\"_blank\">Dev-1(96)</a>, <a href=\"https://github.com/jannatulferdus182003\" target=\"_blank\">Dev-2(58)</a>, <a href=\"https://github.com/Badhon63\" target=\"_blank\">Dev-3(63)</a>, Dev-4(93) | <a href=\"https://github.com/oU1TS/sesa.cse55.sadiasemim139-ops.ou1ts\" target=\"_blank\">Fork</a></p>"}'::JSONB, 'approved', 9),
('courses-sesa-Binary-Eclipse', 'courses', '@Helal Uddin Patwary/0432410005101086', 'Binary-Eclipse/Software-Engineering-and-System-Analysis-Project This web-based project, SavePaws Club, helps report and rescue animals by sharing live locations and contacting rescue teams. It offers offline emergency info, pet adoption, a marketplace, vet consultations, blogs, and volunteering. Built with modern web tech, it promotes animal welfare through community and tech. Dev-1(86) , Dev-2(69) , Dev-3(83) , Dev-4(53) | Fork', 'https://github.com/Binary-Eclipse/Software-Engineering-and-System-Analysis-Project', 'https://github.com/Binary-Eclipse/Software-Engineering-and-System-Analysis-Project', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Software Engineering and System Analysis Lab (CSE0613226)']::TEXT[], '{"course_category":"Software Engineering and System Analysis Lab (CSE0613226)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/Binary-Eclipse/Software-Engineering-and-System-Analysis-Project\" target=\"_blank\">@Helal Uddin Patwary/0432410005101086</a><p class-repo-info>Binary-Eclipse/Software-Engineering-and-System-Analysis-Project<br>This web-based project, SavePaws Club, helps report and rescue animals by sharing live locations and contacting rescue teams. It offers offline emergency info, pet adoption, a marketplace, vet consultations, blogs, and volunteering. Built with modern web tech, it promotes animal welfare through community and tech.<br><a href=\"https://github.com/Binary-Eclipse\" target=\"_blank\">Dev-1(86)</a>, <a href=\"https://github.com/jannatulferdus182003\" target=\"_blank\">Dev-2(69)</a>, <a href=\"https://github.com/ORNOB-083\" target=\"_blank\">Dev-3(83)</a>, <a href=\"https://github.com/shamiurhasan100\" target=\"_blank\">Dev-4(53)</a> | <a href=\"https://github.com/oU1TS/Software-Engineering-and-System-Analysis-Project.cse55.Binary-Eclipse.ou1ts\" target=\"_blank\">Fork</a></p>"}'::JSONB, 'approved', 10),
('courses-sesa-ISJPS', 'courses', 'Frontend', 'Frontend | Backend This is the frontend and backend of ISJPS Dev-1(96) , Dev-2 | Fork-1 , Fork-2', 'https://github.com/ISJPS-AI-Security/frontend', 'https://github.com/ISJPS-AI-Security/frontend', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Software Engineering and System Analysis Lab (CSE0613226)']::TEXT[], '{"course_category":"Software Engineering and System Analysis Lab (CSE0613226)","course_icon":"fa-solid fa-code","rawHtml":"<span>@Md. Robiul Hassan (Arriesgado47)/0432310005101096</span><p class-repo-info><a href=\"https://github.com/ISJPS-AI-Security/frontend\" target=\"_blank\">Frontend</a> | <a href=\"https://github.com/ISJPS-AI-Security/backend\" target=\"_blank\">Backend</a><br>This is the frontend and backend of ISJPS<br><a href=\"https://github.com/Arriesgado47\" target=\"_blank\">Dev-1(96)</a>, Dev-2 | <a href=\"https://github.com/oU1TS/frontend_ISJPS-AI-Security.cse55.ou1ts\" target=\"_blank\">Fork-1</a>, <a href=\"https://github.com/oU1TS/backend_ISJPS-AI-Security.cse55.ou1ts\" target=\"_blank\">Fork-2</a></p>"}'::JSONB, 'approved', 11),
('courses-spdd-b1tranger', 'courses', '@b1tranger/0432410005101088', 'b1tranger/CSE0613316-SPDD-Project-Design', 'https://github.com/b1tranger/CSE0613316-SPDD-Project-Design', 'https://github.com/b1tranger/CSE0613316-SPDD-Project-Design', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Software Project Design and Development Lab (CSE0613316)']::TEXT[], '{"course_category":"Software Project Design and Development Lab (CSE0613316)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/b1tranger/CSE0613316-SPDD-Project-Design\" target=\"_blank\">@b1tranger/0432410005101088</a><p>b1tranger/CSE0613316-SPDD-Project-Design</p>"}'::JSONB, 'approved', 12),
('courses-ai-b1tranger', 'courses', '@b1tranger/0432410005101088', 'b1tranger/CSE0613312-AI-Lab', 'https://github.com/b1tranger/CSE0613312-AI-Lab', 'https://github.com/b1tranger/CSE0613312-AI-Lab', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Artificial Intelligence Lab (CSE0613312)']::TEXT[], '{"course_category":"Artificial Intelligence Lab (CSE0613312)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/b1tranger/CSE0613312-AI-Lab\" target=\"_blank\">@b1tranger/0432410005101088</a><p>b1tranger/CSE0613312-AI-Lab</p>"}'::JSONB, 'approved', 13),
('courses-cg-monotheist', 'courses', 'Md. Masud Rahman (@Monotheist0)/0432320005101064', 'Monotheist0/CSE358-ComputerGraphics-Lab--0432320005101064- This repository contains the lab assignments for the CSE 358 course. Fork', 'https://github.com/Monotheist0/CSE358-ComputerGraphics-Lab--0432320005101064-', 'https://github.com/Monotheist0/CSE358-ComputerGraphics-Lab--0432320005101064-', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Computer Graphics & Multimedia Lab (CSE 358)']::TEXT[], '{"course_category":"Computer Graphics & Multimedia Lab (CSE 358)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/Monotheist0/CSE358-ComputerGraphics-Lab--0432320005101064-\" target=\"_blank\">Md. Masud Rahman (@Monotheist0)/0432320005101064</a><p>Monotheist0/CSE358-ComputerGraphics-Lab--0432320005101064-<br>This repository contains the lab assignments for the CSE 358 course.<br><a href=\"https://github.com/oU1TS/CSE358-ComputerGraphics-Lab.Monotheist0.cse54\" target=\"_blank\">Fork</a></p>"}'::JSONB, 'approved', 14),
('courses-cg-Arriesgado47', 'courses', 'Md. Robiul Hassan (Arriesgado47)/0432310005101096', 'Arriesgado47/Graphics-Lab Here, all the assignments will be alligned and updated throughout the course time... Have a look to find anything that you may need, specially if you are from UITS! Fork', 'https://github.com/Arriesgado47/Graphics-Lab', 'https://github.com/Arriesgado47/Graphics-Lab', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Computer Graphics & Multimedia Lab (CSE 358)']::TEXT[], '{"course_category":"Computer Graphics & Multimedia Lab (CSE 358)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/Arriesgado47/Graphics-Lab\" target=\"_blank\">Md. Robiul Hassan (Arriesgado47)/0432310005101096</a><p class=\"repo-info\">Arriesgado47/Graphics-Lab<br>Here, all the assignments will be alligned and updated throughout the course time... Have a look to find anything that you may need, specially if you are from UITS!<br><a href=\"https://github.com/oU1TS/Graphics-Lab.ou1ts.cse53.Arriesgado47\" target=\"_blank\">Fork</a></p>"}'::JSONB, 'approved', 15),
('courses-cg-4xrhd', 'courses', 'Kazi Md Azhar Uddin Abeer (4xrhd)/Azhar_uddin1120@uits.edu.bd', '4xrhd/Computer Graphics & Multimedia This project contains a series of lab exercises and assignments focused on modern OpenGL (3.3 Core Profile) and real-time graphics rendering. Fork', 'https://github.com/4xrhd/CGM_LAB', 'https://github.com/4xrhd/CGM_LAB', '{"type":"icon","class":"fa-brands fa-github"}'::JSONB, '[]'::JSONB, ARRAY['Computer Graphics & Multimedia Lab (CSE 358)']::TEXT[], '{"course_category":"Computer Graphics & Multimedia Lab (CSE 358)","course_icon":"fa-solid fa-code","rawHtml":"<a href=\"https://github.com/4xrhd/CGM_LAB\" target=\"_blank\">Kazi Md Azhar Uddin Abeer (4xrhd)/Azhar_uddin1120@uits.edu.bd</a><p class=\"repo-info\">4xrhd/Computer Graphics & Multimedia<br>This project contains a series of lab exercises and assignments focused on modern OpenGL (3.3 Core Profile) and real-time graphics rendering.<br><a href=\"https://github.com/oU1TS/CGM_LAB.4xrhd.cse54.ou1ts\" target=\"_blank\">Fork</a></p>"}'::JSONB, 'approved', 16),
('capstone-uits-portal', 'capstones', 'oU1TS Academic & Social Portal', 'A centralized SPA web application designed for UITS students to share academic resources, find project partners, and connect with mentors in the tech industry.', 'https://github.com/b1tranger/ou1ts.portal', 'https://github.com/b1tranger/ou1ts.portal', '{"type":"image","src":"oU1TS-portal.webp"}'::JSONB, '[{"label":"Demo","url":"https://github.com/b1tranger/ou1ts.portal"}]'::JSONB, ARRAY['SPA', 'Vanilla JS', 'Supabase', 'CSS3']::TEXT[], '{"batch":"Batch 51","semester":"Fall 2025","team":["Shamiur Hasan","GSM Urady"],"image":"oU1TS-portal.webp","repoUrl":"https://github.com/b1tranger/ou1ts.portal"}'::JSONB, 'approved', 1),
('capstone-blood-donation', 'capstones', 'Blood Donation & Urgent Alert Network', 'An emergency blood matching platform that utilizes geographical locations to connect local donors with UITS community members in critical health situations.', 'https://bd-ou1ts.netlify.app/', 'https://bd-ou1ts.netlify.app/', '{"type":"image","src":"tools-icon/logo-bd.png"}'::JSONB, '[{"label":"Demo","url":"https://bd-ou1ts.netlify.app/"}]'::JSONB, ARRAY['Node.js', 'Express', 'MongoDB', 'Geolocation']::TEXT[], '{"batch":"Batch 51","semester":"Fall 2025","team":["Robiul Islam","Akib Reza"],"image":"tools-icon/logo-bd.png","repoUrl":"https://bd-ou1ts.netlify.app/"}'::JSONB, 'approved', 2),
('capstone-cyber-sec-wing', 'capstones', 'Cyber Security Resource & Lab Simulator', 'An interactive environment featuring sandboxed challenges for training students in penetration testing, threat hunting, and modern cybersecurity protocols.', 'https://uitssec.github.io/', 'https://uitssec.github.io/', '{"type":"image","src":"https://res.cloudinary.com/b1tranger/image/upload/v1757773769/nobg_UITS_Cyber_Security_Wing_FB_logo_admu5c.png"}'::JSONB, '[{"label":"Demo","url":"https://uitssec.github.io/"}]'::JSONB, ARRAY['Docker', 'Go', 'React', 'Linux Sandbox']::TEXT[], '{"batch":"Batch 52","semester":"Spring 2026","team":["Sadiasemim","Masud Rahman"],"image":"https://res.cloudinary.com/b1tranger/image/upload/v1757773769/nobg_UITS_Cyber_Security_Wing_FB_logo_admu5c.png","repoUrl":"https://uitssec.github.io/"}'::JSONB, 'approved', 3),
('capstone-uits-bot', 'capstones', 'UITS Bot & Routine Automation System', 'A utility ecosystem for student routine formatting, automatic CGPA tracking, and handwritten lecture notes storage using Telegram API integration.', 'http://akibreza.github.io/uitsBOT', 'http://akibreza.github.io/uitsBOT', '{"type":"image","src":"materials-icon/UITS-Bot.webp"}'::JSONB, '[{"label":"Demo","url":"http://akibreza.github.io/uitsBOT"}]'::JSONB, ARRAY['Python', 'Telegram Bot', 'PostgreSQL', 'CRON Scheduler']::TEXT[], '{"batch":"Batch 50","semester":"Spring 2025","team":["Akib Reza","Sayra Rahman"],"image":"materials-icon/UITS-Bot.webp","repoUrl":"http://akibreza.github.io/uitsBOT"}'::JSONB, 'approved', 4),
('capstone-research-archive', 'capstones', 'Academic Research & Thesis Repository', 'A collaborative platform dedicated to cataloging and storing research drafts, undergraduate thesis works, and publication articles from UITS CSE.', 'https://research-uits.rf.gd/', 'https://research-uits.rf.gd/', '{"type":"image","src":"materials-icon/b1t-acad.webp"}'::JSONB, '[{"label":"Demo","url":"https://research-uits.rf.gd/"}]'::JSONB, ARRAY['PHP', 'MySQL', 'Tailwind CSS', 'PDF indexing']::TEXT[], '{"batch":"Batch 52","semester":"Spring 2026","team":["Ayman Rahman","Lamia Kawsar"],"image":"materials-icon/b1t-acad.webp","repoUrl":"https://research-uits.rf.gd/"}'::JSONB, 'approved', 5),
('capstone-uni-scheduler', 'capstones', 'Smart Academic Calendar & Room Allocator', 'A responsive planning tool built to prevent timetable conflicts and optimize class allocations across UITS campuses dynamically.', 'https://university-companion.netlify.app/', 'https://university-companion.netlify.app/', '{"type":"image","src":"icons/logo.png"}'::JSONB, '[{"label":"Demo","url":"https://university-companion.netlify.app/"}]'::JSONB, ARRAY['JavaScript', 'Calendar APIs', 'CSS Grid', 'localStorage']::TEXT[], '{"batch":"Batch 50","semester":"Spring 2025","team":["Zirconium","Jahirul Islam"],"image":"icons/logo.png","repoUrl":"https://university-companion.netlify.app/"}'::JSONB, 'approved', 6),
('mentor-sakib', 'mentors', 'Md. Sakib Hosen', 'Software Engineer at Google (Batch 48 Alumni). 3+ years in Cloud Infrastructure', 'https://linkedin.com/in/sakib-hosen-uits', 'https://linkedin.com/in/sakib-hosen-uits', '{"type":"text","text":"M"}'::JSONB, '[]'::JSONB, ARRAY['Go', 'Kubernetes', 'GCP', 'Python']::TEXT[], '{"name":"Md. Sakib Hosen","title":"Software Engineer","company":"Google","batch":"Batch 48 Alumni","experience":"3+ years in Cloud Infrastructure","stars":5,"email":"md.sakib.hos3n@gmail.com","socials":{"linkedin":"https://linkedin.com/in/sakib-hosen-uits","github":"https://github.com/mdsakibhosen","telegram":"https://t.me/sakib_hosen"},"skills":["Go","Kubernetes","GCP","Python"]}'::JSONB, 'approved', 1),
('mentor-shamiur', 'mentors', 'Shamiur Hasan', 'Full Stack Developer at Brain Station 23 (Batch 50 Alumni). 2+ years in Web Solutions', 'https://linkedin.com/in/shamiur-hasan', 'https://linkedin.com/in/shamiur-hasan', '{"type":"text","text":"S"}'::JSONB, '[]'::JSONB, ARRAY['React', 'Node.js', 'GraphQL', 'AWS']::TEXT[], '{"name":"Shamiur Hasan","title":"Full Stack Developer","company":"Brain Station 23","batch":"Batch 50 Alumni","experience":"2+ years in Web Solutions","stars":5,"email":"shamiurhasan100@gmail.com","socials":{"linkedin":"https://linkedin.com/in/shamiur-hasan","github":"https://github.com/shamiurhasan","telegram":"https://t.me/shamiur_hasan"},"skills":["React","Node.js","GraphQL","AWS"]}'::JSONB, 'approved', 2),
('mentor-masud', 'mentors', 'Masud Rahman', 'Mobile App Engineer at Pathao (Batch 49 Alumni). 3 years in Flutter/iOS', 'https://linkedin.com/in/masudrahman', 'https://linkedin.com/in/masudrahman', '{"type":"text","text":"M"}'::JSONB, '[]'::JSONB, ARRAY['Flutter', 'Dart', 'Swift', 'Firebase']::TEXT[], '{"name":"Masud Rahman","title":"Mobile App Engineer","company":"Pathao","batch":"Batch 49 Alumni","experience":"3 years in Flutter/iOS","stars":4,"email":"masudrahman998@gmail.com","socials":{"linkedin":"https://linkedin.com/in/masudrahman","github":"https://github.com/masudrahman","telegram":"https://t.me/masud_rahman"},"skills":["Flutter","Dart","Swift","Firebase"]}'::JSONB, 'approved', 3),
('mentor-ayman', 'mentors', 'Ayman Rahman', 'DevOps Architect at Selise (Batch 51 Alumni). 2 years in CI/CD Automation', 'https://linkedin.com/in/ayman-rahman', 'https://linkedin.com/in/ayman-rahman', '{"type":"text","text":"A"}'::JSONB, '[]'::JSONB, ARRAY['Docker', 'Jenkins', 'Terraform', 'Linux']::TEXT[], '{"name":"Ayman Rahman","title":"DevOps Architect","company":"Selise","batch":"Batch 51 Alumni","experience":"2 years in CI/CD Automation","stars":4,"email":"ayman788.9812@gmail.com","socials":{"linkedin":"https://linkedin.com/in/ayman-rahman","github":"https://github.com/ayman788","telegram":"https://t.me/ayman_rahman"},"skills":["Docker","Jenkins","Terraform","Linux"]}'::JSONB, 'approved', 4),
('mentor-sayra', 'mentors', 'Sayra Rahman', 'UI/UX Designer at TigerIT (Batch 50 Alumni). 2+ years in Product Design', 'https://linkedin.com/in/sayra-rahman', 'https://linkedin.com/in/sayra-rahman', '{"type":"text","text":"S"}'::JSONB, '[]'::JSONB, ARRAY['Figma', 'Adobe XD', 'User Research', 'Prototyping']::TEXT[], '{"name":"Sayra Rahman","title":"UI/UX Designer","company":"TigerIT","batch":"Batch 50 Alumni","experience":"2+ years in Product Design","stars":5,"email":"sayrarahman00@gmail.com","socials":{"linkedin":"https://linkedin.com/in/sayra-rahman","github":"https://github.com/sayra00","telegram":"https://t.me/sayra_designer"},"skills":["Figma","Adobe XD","User Research","Prototyping"]}'::JSONB, 'approved', 5),
('talent-gsm', 'talent', 'GSM Urady', 'Ambitious frontend developer passionate about building premium, high-fidelity responsive user interfaces and modern Single Page Applications.', 'https://linkedin.com/in/gsm-urady', 'https://linkedin.com/in/gsm-urady', '{"type":"text","text":"G"}'::JSONB, '[]'::JSONB, ARRAY['JavaScript', 'CSS3', 'React', 'HTML5']::TEXT[], '{"name":"GSM Urady","role":"Frontend Developer","sector":"Web Development","bio":"Ambitious frontend developer passionate about building premium, high-fidelity responsive user interfaces and modern Single Page Applications.","skills":["JavaScript","CSS3","React","HTML5"],"socials":{"linkedin":"https://linkedin.com/in/gsm-urady","github":"https://github.com/gsmurady123","telegram":"https://t.me/gsm_urady","email":"gsmurady123@gmail.com"}}'::JSONB, 'approved', 1),
('talent-mahi', 'talent', 'Ismiuddin Mahi', 'Backend architecture enthusiast specialized in structured API design, relational databases, and secure authentication models.', 'https://linkedin.com/in/ismiuddin-mahi', 'https://linkedin.com/in/ismiuddin-mahi', '{"type":"text","text":"I"}'::JSONB, '[]'::JSONB, ARRAY['Node.js', 'Express', 'PostgreSQL', 'REST APIs']::TEXT[], '{"name":"Ismiuddin Mahi","role":"Backend Engineer","sector":"Web Development","bio":"Backend architecture enthusiast specialized in structured API design, relational databases, and secure authentication models.","skills":["Node.js","Express","PostgreSQL","REST APIs"],"socials":{"linkedin":"https://linkedin.com/in/ismiuddin-mahi","github":"https://github.com/ismiuddinmahi25","telegram":"https://t.me/ismiuddin_mahi","email":"ismiuddinmahi25@gmail.com"}}'::JSONB, 'approved', 2),
('talent-lamia', 'talent', 'Lamia Kawsar', 'Cross-platform mobile application designer focusing on fluid gestures, smooth transitions, and local database caching techniques.', 'https://linkedin.com/in/lamia-kawsar', 'https://linkedin.com/in/lamia-kawsar', '{"type":"text","text":"L"}'::JSONB, '[]'::JSONB, ARRAY['Flutter', 'Dart', 'Firebase', 'State Management']::TEXT[], '{"name":"Lamia Kawsar","role":"Mobile Developer","sector":"Mobile Apps","bio":"Cross-platform mobile application designer focusing on fluid gestures, smooth transitions, and local database caching techniques.","skills":["Flutter","Dart","Firebase","State Management"],"socials":{"linkedin":"https://linkedin.com/in/lamia-kawsar","github":"https://github.com/lamiakawsar0593","telegram":"https://t.me/lamia_kawsar","email":"lamiakawsar0593@gmail.com"}}'::JSONB, 'approved', 3),
('talent-sayra', 'talent', 'Sayra Rahman', 'Creating high-fidelity mockups, responsive grid systems, and user-centric wireframes for corporate websites and mobile apps.', 'https://linkedin.com/in/sayra-rahman', 'https://linkedin.com/in/sayra-rahman', '{"type":"text","text":"S"}'::JSONB, '[]'::JSONB, ARRAY['Figma', 'Wireframing', 'User Journeys', 'CSS Grid']::TEXT[], '{"name":"Sayra Rahman","role":"UI/UX & Product Designer","sector":"UI/UX Design","bio":"Creating high-fidelity mockups, responsive grid systems, and user-centric wireframes for corporate websites and mobile apps.","skills":["Figma","Wireframing","User Journeys","CSS Grid"],"socials":{"linkedin":"https://linkedin.com/in/sayra-rahman","github":"https://github.com/sayrarahman00","telegram":"https://t.me/sayrarahman","email":"sayrarahman00@gmail.com"}}'::JSONB, 'approved', 4),
('talent-supto', 'talent', 'Md. Supto', 'Building data intelligence pipelines and predictive machine learning models to solve complex real-world classification problems.', 'https://linkedin.com/in/mdsupto', 'https://linkedin.com/in/mdsupto', '{"type":"text","text":"M"}'::JSONB, '[]'::JSONB, ARRAY['Python', 'TensorFlow', 'Pandas', 'Scikit-Learn']::TEXT[], '{"name":"Md. Supto","role":"AI/ML Engineer","sector":"AI/ML & Data Science","bio":"Building data intelligence pipelines and predictive machine learning models to solve complex real-world classification problems.","skills":["Python","TensorFlow","Pandas","Scikit-Learn"],"socials":{"linkedin":"https://linkedin.com/in/mdsupto","github":"https://github.com/mdsupto718","telegram":"https://t.me/mdsupto","email":"mdsupto718@gmail.com"}}'::JSONB, 'approved', 5)
ON CONFLICT (id) DO UPDATE SET
    category = EXCLUDED.category,
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    url = EXCLUDED.url,
    copy_url = EXCLUDED.copy_url,
    icon = EXCLUDED.icon,
    links = EXCLUDED.links,
    tags = EXCLUDED.tags,
    extra_data = EXCLUDED.extra_data,
    status = EXCLUDED.status,
    sort_order = EXCLUDED.sort_order,
    updated_at = NOW();

-- ----------------------------------------------------------------------------
-- STEP 7: Instructions for Initial Admin Role Setup
-- ----------------------------------------------------------------------------
-- To make your user the default Portal Admin, run:
-- UPDATE public.profiles
-- SET is_portal_admin = true
-- WHERE email = 'your.email@uits.edu.bd';
