-- ============================================================================
-- oU1TS Centralized Supabase Database: Unified Setup & Portal Stars Schema
-- Location: doc/db/portal_central_database_setup.sql
-- Companion File: doc/query/query-4-central-db-portal-stars.sql
-- ============================================================================

-- 1. Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  full_name TEXT,
  student_id TEXT,
  department TEXT,
  batch TEXT,
  blood_group TEXT,
  social_facebook TEXT,
  social_instagram TEXT,
  social_telegram TEXT,
  social_discord TEXT,
  project_tags TEXT[] DEFAULT ARRAY['root']::TEXT[],
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  CONSTRAINT check_student_id_numeric_or_oauth 
    CHECK (student_id ~ '^[0-9]+$' OR student_id = 'OAUTH_USER' OR student_id IS NULL),
  
  CONSTRAINT check_blood_group_valid 
    CHECK (blood_group IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-') OR blood_group IS NULL)
);

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own profile" ON public.profiles;
CREATE POLICY "Users can view own profile" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Service role can insert profiles" ON public.profiles;
CREATE POLICY "Service role can insert profiles" ON public.profiles
  FOR INSERT WITH CHECK (true);

DROP INDEX IF EXISTS profiles_student_id_unique;
CREATE UNIQUE INDEX IF NOT EXISTS profiles_student_id_unique
  ON public.profiles (student_id)
  WHERE student_id IS NOT NULL AND student_id <> 'OAUTH_USER';

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (
    id, 
    student_id, 
    email, 
    full_name, 
    department,
    blood_group,
    project_tags
  )
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'student_id', 'OAUTH_USER'),
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', NULL),
    COALESCE(NEW.raw_user_meta_data->>'department', NULL),
    COALESCE(NEW.raw_user_meta_data->>'blood_group', NULL),
    ARRAY['root', 'portal']::TEXT[]
  )
  ON CONFLICT (id) DO UPDATE SET
    project_tags = array_append(public.profiles.project_tags, 'portal')
    WHERE NOT ('portal' = ANY(public.profiles.project_tags));
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.add_project_tag(tag TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.profiles
  SET project_tags = array_append(project_tags, tag),
      updated_at = NOW()
  WHERE id = auth.uid()
    AND NOT (tag = ANY(project_tags));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;


-- 2. Stars Table for JSON Resources
CREATE TABLE IF NOT EXISTS public.stars (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  resource_type TEXT NOT NULL,
  resource_id TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT unique_user_resource_star UNIQUE (user_id, resource_type, resource_id)
);

CREATE INDEX IF NOT EXISTS idx_stars_resource ON public.stars(resource_type, resource_id);
CREATE INDEX IF NOT EXISTS idx_stars_user ON public.stars(user_id);
CREATE INDEX IF NOT EXISTS idx_stars_created ON public.stars(created_at DESC);

ALTER TABLE public.stars ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view star counts" ON public.stars;
CREATE POLICY "Anyone can view star counts" ON public.stars
  FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can star" ON public.stars;
CREATE POLICY "Authenticated users can star" ON public.stars
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can unstar own stars" ON public.stars;
CREATE POLICY "Users can unstar own stars" ON public.stars
  FOR DELETE USING (auth.uid() = user_id);


-- 3. Analytics View & Ranking Functions
CREATE OR REPLACE VIEW public.resource_star_rankings AS
SELECT 
  s.resource_type,
  s.resource_id,
  COUNT(*)::INTEGER AS total_stars,
  DENSE_RANK() OVER (PARTITION BY s.resource_type ORDER BY COUNT(*) DESC) AS category_rank,
  DENSE_RANK() OVER (ORDER BY COUNT(*) DESC) AS global_rank
FROM public.stars s
GROUP BY s.resource_type, s.resource_id;

CREATE OR REPLACE FUNCTION public.get_category_rankings(target_type TEXT)
RETURNS TABLE (
  resource_id TEXT,
  total_stars INTEGER,
  category_rank BIGINT
) LANGUAGE sql STABLE SECURITY DEFINER AS $$
  SELECT 
    resource_id,
    total_stars,
    category_rank
  FROM public.resource_star_rankings
  WHERE resource_type = target_type
  ORDER BY total_stars DESC, resource_id ASC;
$$;

CREATE OR REPLACE FUNCTION public.get_user_star_metrics(target_user_id UUID)
RETURNS JSON LANGUAGE plpgsql STABLE SECURITY DEFINER AS $$
DECLARE
  result JSON;
BEGIN
  SELECT json_build_object(
    'total_starred', COUNT(*),
    'categories', (
      SELECT json_object_agg(resource_type, cat_count)
      FROM (
        SELECT resource_type, COUNT(*) AS cat_count
        FROM public.stars
        WHERE user_id = target_user_id
        GROUP BY resource_type
      ) sub
    )
  ) INTO result
  FROM public.stars
  WHERE user_id = target_user_id;

  RETURN result;
END;
$$;

-- 4. Featured Projects Table
CREATE TABLE IF NOT EXISTS public.featured_projects (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug TEXT UNIQUE NOT NULL,
  title TEXT NOT NULL,
  category TEXT NOT NULL DEFAULT 'Initiative',
  description TEXT,
  url TEXT NOT NULL,
  img TEXT,
  icon TEXT,
  alt TEXT,
  rank_score INTEGER NOT NULL DEFAULT 100 CHECK (rank_score >= 0),
  views_count INTEGER NOT NULL DEFAULT 0,
  stars_count INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_featured_projects_ranking ON public.featured_projects (rank_score DESC, stars_count DESC);
CREATE INDEX IF NOT EXISTS idx_featured_projects_active ON public.featured_projects (is_active);

ALTER TABLE public.featured_projects ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can view active featured projects" ON public.featured_projects;
CREATE POLICY "Anyone can view active featured projects" ON public.featured_projects
  FOR SELECT USING (is_active = true);

DROP POLICY IF EXISTS "Service role can modify featured projects" ON public.featured_projects;
CREATE POLICY "Service role can modify featured projects" ON public.featured_projects
  FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

